schema = 3

[mod]
  [mod."github.com/BurntSushi/toml"]
    version = "v1.4.0"
    hash = "sha256-3cr8hfVA4th/AfveHDxigmj8Eiiae0ZBnxAgy+7RYO4="
  [mod."github.com/atotto/clipboard"]
    version = "v0.1.4"
    hash = "sha256-ZZ7U5X0gWOu8zcjZcWbcpzGOGdycwq0TjTFh/eZHjXk="
  [mod."github.com/charmbracelet/bubbles/v2"]
    version = "v2.0.0-alpha.2"
    hash = "sha256-SfSV3CCFhTWkO1RSsk0pnFtHOAclLekaNaXFyNoLuXI="
  [mod."github.com/charmbracelet/bubbletea/v2"]
    version = "v2.0.0-alpha.2"
    hash = "sha256-eWAuc8n+U3WiFHPAPm+YI57nso6KA0MCZqZfF5hr71E="
  [mod."github.com/charmbracelet/colorprofile"]
    version = "v0.1.6"
    hash = "sha256-dKI5ulOOZotagRY9x5baP+GLL0nydqZDxEZDGMQk+Uk="
  [mod."github.com/charmbracelet/lipgloss/v2"]
    version = "v2.0.0-alpha.2"
    hash = "sha256-DoFFftclaTTOpino7WfFBAiAVyCS4rQ6n6gXMp40Jhg="
  [mod."github.com/charmbracelet/x/ansi"]
    version = "v0.4.3"
    hash = "sha256-L8+W7dZvb1HmnEdhHG1bPqF2lsz5hmLkfj8zuuIEdhU="
  [mod."github.com/charmbracelet/x/cellbuf"]
    version = "v0.0.3"
    hash = "sha256-KIumRvjFz5OHvezYk6uqG7tvqB3JdVAt9uN8i0Vu17M="
  [mod."github.com/charmbracelet/x/term"]
    version = "v0.2.0"
    hash = "sha256-eIsmNg/ktYEFWG9j/z2FuD+iizkV+HGLrUvor7Xkqlo="
  [mod."github.com/charmbracelet/x/wcwidth"]
    version = "v0.0.0-20241011142426-46044092ad91"
    hash = "sha256-YwjJRjPcz2wuz9jDbJ+0ZTIMYiRKuOyCwcClia8vArg="
  [mod."github.com/charmbracelet/x/windows"]
    version = "v0.2.0"
    hash = "sha256-pDAd1E5w66E/d3vuTyzgnW+W/KegZ2sxQQMfoEn7S1A="
  [mod."github.com/lucasb-eyer/go-colorful"]
    version = "v1.2.0"
    hash = "sha256-Gg9dDJFCTaHrKHRR1SrJgZ8fWieJkybljybkI9x0gyE="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.16"
    hash = "sha256-NC+ntvwIpqDNmXb7aixcg09il80ygq6JAnW0Gb5b/DQ="
  [mod."github.com/muesli/cancelreader"]
    version = "v0.2.2"
    hash = "sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.7"
    hash = "sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo="
  [mod."github.com/sahilm/fuzzy"]
    version = "v0.1.1"
    hash = "sha256-f2VsDI6G+V2w31tSDzbZPi9EI2E7jRV6Aq8yeOorSZY="
  [mod."github.com/xo/terminfo"]
    version = "v0.0.0-20220910002029-abceb7e1c41e"
    hash = "sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU="
  [mod."golang.org/x/sync"]
    version = "v0.8.0"
    hash = "sha256-usvF0z7gq1vsX58p4orX+8WHlv52pdXgaueXlwj2Wss="
  [mod."golang.org/x/sys"]
    version = "v0.26.0"
    hash = "sha256-YjklsWNhx4g4TaWRWfFe1TMFKujbqiaNvZ38bfI35fM="
  [mod."golang.org/x/text"]
    version = "v0.19.0"
    hash = "sha256-C92pSYLLUQ2NKKcc60wpoSJ5UWAfnWkmd997C13fXdU="
